# Generated by Django 3.0.4 on 2020-05-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='/media/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
