# Generated by Django 3.0.4 on 2020-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200529_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
